name: Tests et Déploiement

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v --tb=short --cov=src --cov-report=xml --cov-report=term
      env:
        # Variables d'environnement pour les tests (valeurs fictives)
        NOTION_API_KEY: "test_notion_key"
        NOTION_DATABASE_ID: "test_db_id"
        SEUILS_DATABASE_ID: "test_seuils_db_id"
        POLYGON_API_KEY: "test_polygon_key"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
    
    - name: Lint code
      run: |
        pip install flake8
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test success confirmation
      run: |
        echo "✅ All tests passed successfully!"
        echo "✅ Code quality checks passed!"
        echo "🔓 Ready for deployment pipeline!"

  deploy:
    needs: [test, security]  # Attendre que test ET security passent
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && success()  # Déployer seulement si tout est OK
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validate deployment readiness
      run: |
        echo "✅ Tests passed successfully"
        echo "✅ Security checks passed"
        echo "🚀 Ready for deployment to Render"
    
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
    
    - name: Deployment success notification
      if: success()
      run: |
        echo "🎉 Deployment to Render completed successfully!"
        echo "Bot version with all tests passing is now live."
    
    - name: Deployment failure notification  
      if: failure()
      run: |
        echo "❌ Deployment to Render failed!"
        echo "Check Render logs for details."

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety bandit
    
    - name: Security check
      run: |
        safety check
        bandit -r src/ -f json -o bandit-report.json || true
    
    - name: Upload security report
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: bandit-report.json
